apiVersion: apps/v1
kind: Deployment
metadata:
  name: k9s
  labels:
    app: k9s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k9s
  template:
    metadata:
      labels:
        app: k9s
    spec:
      containers:
        - name: k9s
          image: derailed/k9s
          command: ["k9s"]
          tty: true
          stdin: true
          env:
            - name: ISTIO_NAMESPACE
              value: istio-system
          volumeMounts:
            - name: kiali-config
              mountPath: /root/.kiali
              readOnly: true
      volumes:
        - name: kiali-config
          configMap:
            name: kiali-config
